networks:
  bigdata_net:
    driver: bridge

volumes:
  hdfs_namenode:
  hdfs_datanode_1:
  hdfs_datanode_2:
  hdfs_datanode_3:
  metastore_db:
  mongo_data:

services:
  # MongoDB avec données d'exemple
  mongodb:
    image: mongo:7
    container_name: mongodb_new
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks: [bigdata_net]
    environment:
      - MONGO_INITDB_DATABASE=retail
    restart: unless-stopped

  # Interface web MongoDB
  mongo-express:
    image: mongo-express:1
    container_name: mongo-express_new
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_new
      - ME_CONFIG_MONGODB_DATABASE=retail
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8089:8081"
    depends_on: [mongodb]
    networks: [bigdata_net]
    restart: unless-stopped

  # Application Streamlit simplifiée
  app:
    image: python:3.11-slim
    container_name: app_new
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    networks: [bigdata_net]
    environment:
      - MONGO_URI=mongodb://mongodb_new:27017
      - MONGO_DB=retail
      - MONGO_COLLECTION=sales
    command: >
      bash -c "
        pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org streamlit pandas plotly pymongo &&
        streamlit run app.py --server.port 8501 --server.address 0.0.0.0
      "
    depends_on: [mongodb]
    restart: unless-stopped


