services:
  spark-worker-test:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-test
    hostname: spark-worker-test
    environment:
      - SPARK_MASTER_URL=spark://namenode:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./spark/test-worker.sh:/test-worker.sh
    ports:
      - "8090:8081"
    depends_on: [namenode]
    restart: unless-stopped
    command: ["/test-worker.sh"]
    networks: [bigdata_net]

networks:
  bigdata_net:
    external: true
