networks:
  bigdata_net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks: [bigdata_net]
    environment:
      - MONGO_INITDB_DATABASE=retail
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_DATABASE=retail
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8090:8081"
    depends_on: [mongodb]
    networks: [bigdata_net]
    restart: unless-stopped

  app:
    image: python:3.11-slim
    container_name: app
    working_dir: /app
    ports:
      - "8502:8501"
    volumes:
      - ./app:/app
    networks: [bigdata_net]
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=retail
      - MONGO_COLLECTION=sales
    command: >
      bash -c "
        pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org streamlit pandas plotly pymongo &&
        streamlit run app.py --server.port 8501 --server.address 0.0.0.0
      "
    depends_on: [mongodb]
    restart: unless-stopped

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: [bigdata_net]
    restart: unless-stopped

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    depends_on: [spark-master]
    networks: [bigdata_net]
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [bigdata_net]
    restart: unless-stopped
