#!/bin/bash

echo "🚀 Test Final des Workers Spark"
echo "==============================="

echo ""
echo "1. Vérification de l'état du cluster..."
echo "   - Spark Master: http://localhost:8085"
echo "   - HDFS NameNode: http://localhost:9870"
echo "   - Application Streamlit: http://localhost:8501"

echo ""
echo "2. Test du traitement Spark local..."
docker exec app bash -c "export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && python /app/exemple-simple.py"

echo ""
echo "3. Exemples de travail que les Workers Spark peuvent effectuer :"
echo ""
echo "📊 ANALYSES POSSIBLES :"
echo "   - Analyse des ventes par catégorie"
echo "   - Top produits les plus vendus"
echo "   - Utilisateurs les plus actifs"
echo "   - Tendances temporelles"
echo "   - Détection de patterns"
echo "   - Segmentation des clients"
echo "   - Prédiction de tendances"
echo "   - Corrélations entre produits"

echo ""
echo "🔧 CONFIGURATION DES WORKERS :"
echo "   - Worker 1: 2G RAM, 2 cores (Port 8091)"
echo "   - Worker 2: 1G RAM, 1 core (Port 8092)"
echo "   - Worker 3: 1G RAM, 1 core (Port 8093)"

echo ""
echo "💻 UTILISATION :"
echo "   - Via l'application Streamlit: http://localhost:8501"
echo "   - Page '⚡ Analyses Spark'"
echo "   - Sélection du type d'analyse"
echo "   - Contrôle de la taille d'échantillon"

echo ""
echo "📈 AVANTAGES DU TRAITEMENT DISTRIBUÉ :"
echo "   - Traitement parallèle de grandes quantités de données"
echo "   - Scalabilité horizontale"
echo "   - Tolérance aux pannes"
echo "   - Performance optimisée"
echo "   - Répartition de charge automatique"

echo ""
echo "✅ Test terminé avec succès !"
echo ""
echo "🎯 Prochaines étapes :"
echo "   1. Démarrer les workers Spark : docker-compose up -d spark-worker-1 spark-worker-2 spark-worker-3"
echo "   2. Utiliser l'application Streamlit pour les analyses"
echo "   3. Monitorer via Spark Master UI"
echo "   4. Sauvegarder les résultats sur HDFS"
